apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.appName}}-ingress
  namespace: ashraful
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - k8s-ashraful.rfft.nl
      secretName: {{.Values.appName}}-cert
  rules:
    - host: k8s-ashraful.rfft.nl
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{.Values.appName}}-service
                port:
                  number: {{.Values.servicePort}}
