apiVersion: v1
kind: Service
metadata:
  name: {{.values.appName}}-service
  namespace: ashraful
spec:
  type: NodePort
  selector:
    app: {{.values.appName}}
  ports:
    - port: {{.values.servicePort}}
      targetPort: {{.values.containerPort}}


